/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checklanguage;

import java.awt.im.InputContext;

/**
 *
 * @author Exorcist
 */
public class MainFrame extends javax.swing.JFrame {

    private javax.swing.JFrame parent;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(javax.swing.JFrame parent) {
        this.parent = parent;
        initComponents();
        if(parent != null) {
            langLabel.setText( "Parent language is " + parent.getInputContext().getLocale().toString() );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        langLabel = new javax.swing.JLabel();
        getLanguageButton = new javax.swing.JButton();
        testTextField = new javax.swing.JTextField();
        newWindowButton = new javax.swing.JButton();
        getParentLanguageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        langLabel.setText("jLabel1");

        getLanguageButton.setText("Get my language");
        getLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLanguageButtonActionPerformed(evt);
            }
        });

        newWindowButton.setText("New window");
        newWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowButtonActionPerformed(evt);
            }
        });

        getParentLanguageButton.setText("Get parent language");
        getParentLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getParentLanguageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(langLabel)
                    .addComponent(testTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getLanguageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getParentLanguageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newWindowButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(langLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getLanguageButton)
                    .addComponent(newWindowButton)
                    .addComponent(getParentLanguageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLanguageButtonActionPerformed
        InputContext ic = InputContext.getInstance();
        langLabel.setText( ic.getLocale().toString() );
    }//GEN-LAST:event_getLanguageButtonActionPerformed

    private void newWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowButtonActionPerformed
        new MainFrame(this).setVisible(true);
    }//GEN-LAST:event_newWindowButtonActionPerformed

    private void getParentLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getParentLanguageButtonActionPerformed
        langLabel.setText( parent.getInputContext().getLocale().toString() );
    }//GEN-LAST:event_getParentLanguageButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getLanguageButton;
    private javax.swing.JButton getParentLanguageButton;
    private javax.swing.JLabel langLabel;
    private javax.swing.JButton newWindowButton;
    private javax.swing.JTextField testTextField;
    // End of variables declaration//GEN-END:variables
}
